<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="shortcut icon" type="imagex/png" href="https://img.icons8.com/fluency/96/000000/ps-controller.png">
    <title>Hangman | How to Play</title>
    <style>
        body{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        h1{
            font-size: 40px;
            margin: 30px 0px 60px;
        }
        h2{
            font-size: 28px;
            margin: 24px 0px;
        }
        h3{
            font-size: 24px;
        }
        p{
            justify-content: center;
            width: 70%;
            font-size: 19px;
        }
        .back{
            position: absolute;
            right: 20px;
            top: 15px;
            padding: 12px 14px;
            background-color: white;
            border: none;
            border-radius: 40px;
            box-shadow: 1px 1px 5px #adadad;
            text-decoration: none;
            transition: 400ms;
            cursor: pointer;
        }
        .back i{
            color: black;
        }
        .back:hover{
            background-color: #ececec;
            box-shadow: 2px 4px 5px #adadad;
        }
    </style>
</head>
<body>
    <a href="/hangman" class="back"><i class="fas fa-arrow-left fa-lg"></i></a>
    <h1>How to Play Hangman</h1>

    <h2>Game Description</h2>
    <p>Hangman is a classic word-guessing game where players try to deduce a hidden word by guessing one letter at a time. The game is both educational and entertaining, often used to help improve spelling, vocabulary, and problem-solving skills.</p>
    <hr>
    <h2>Objective</h2>
    <p>The main objective of Hangman is to guess the hidden word before the player runs out of attempts. Each incorrect guess brings the player closer to completing a drawing of a hangman, which represents the number of remaining guesses.</p>
    <hr>
    <h2>Setup</h2>
    <p><b>Word Selection:</b> If your playing alone, you can choose to play with a random word generated by the game. If you're playing with a friend, one of you chooses a word to the other to guess.</p>
    
</body>
</html>